UnderdogCrew/WhatsApp-Service-BE

login_apis/views.py
- Set precise time boundaries for start and end dates
- Modify start_date to 00:00:00 and end_date to 23:59:59
- Ensure comprehensive time-based filtering for billing data retrieval
=> Enhance UserBillingAPIView date range filtering

ai_apis/views.py, utils/whatsapp_message_data.py
- Restrict threaded message scheduling to a specific user ID
- Add debug print for user information retrieval
- Enhance message sending logic with targeted user-specific handling
=> Add conditional threading for insurance policy message sending

send_scheduled_message.py, utils/whatsapp_message_data.py
- Modify fetch_scheduled_messages to filter messages by a specific user ID
- Remove debug print statement in whatsapp_message_data module
- Improve targeted message scheduling and data retrieval
=> Refine scheduled message retrieval for specific user

utils/whatsapp_message_data.py
- Add robust date handling in send_message_data function
- Convert datetime objects to string format when processing message entries
- Ensure consistent date representation for WhatsApp message scheduling
=> Handle datetime conversion for scheduled message dates

ai_apis/views.py
- Rename 'status' parameter to 'whatsapp_status_text' for clarity
- Update variable references in status filtering logic
- Improve parameter naming to enhance code readability
=> Refactor UserMessageLogs status filtering parameter

ai_apis/views.py
- Replace 'status' parameter check with 'whatsapp_status_text'
- Ensure consistent filtering logic for message status
- Maintain code readability and parameter clarity
=> Update UserMessageLogs status filtering condition

ai_apis/views.py
- Convert whatsapp_status dictionary keys to strings
- Add safety check for whatsapp_status_text key existence
- Improve status filtering robustness and type handling
=> Update WhatsApp status filtering in UserMessageLogs

send_scheduled_message.py, utils/whatsapp_message_data.py
- Update policy generation logic in send_scheduled_message.py and whatsapp_message_data.py
- Add fallback to model-only policy when registration number is empty or None
- Improve policy string formatting for consistent display
=> Handle policy formatting for registration number and model

ai_apis/views.py
- Add robust error handling for datetime conversion
- Support parsing ISO string and timestamp formats
- Provide fallback for datetime conversion failures
- Prevent potential exceptions during message log retrieval
=> Handle multiple datetime parsing scenarios in UserMessageLogs view

ai_apis/views.py
- Enable unrestricted data retrieval for superadmin user
- Modify query filter to return all records when user_id is "superadmin"
- Maintain existing filtering logic for regular users
=> Add superadmin support in UserDashboard query filtering

whatsapp_apis/views.py
- Update message status filtering in chat logs endpoint
- Exclude 'received' status from message type determination
- Simplify message type classification logic
=> Remove 'received' status from CustomersChatLogs message type filtering

utils/whatsapp_message_data.py
- Introduce a check for the presence of "example" in buttons before appending the button entry to the result list
- Maintain existing button parameter structure while improving conditional logic
=> Enhance WhatsApp message processing to conditionally add button entry

whatsapp_apis/views.py
- Introduce a new query parameter 'search' to filter chat list results based on profile name
- Implement case-insensitive regex matching for enhanced search capabilities
- Update aggregation pipeline to include search criteria while retrieving unique messages
=> Add search functionality to UniqueChatList view

whatsapp_apis/views.py
- Simplify the aggregation pipeline by removing unnecessary match conditions for the search parameter
- Enhance customer lookup to include optional name filtering based on the search query
- Update response handling to return a 404 status when no unique chat list is found, improving user feedback
=> Refactor search functionality in UniqueChatList view

whatsapp_apis/views.py
- Update phone number conversion logic to remove spaces before converting to double
- Improve data integrity by ensuring consistent formatting of phone numbers in customer lookup
- Maintain existing search functionality while refining the aggregation pipeline
=> Enhance phone number processing in UniqueChatList view

whatsapp_apis/views.py
- Add checks to ensure profile names are valid before appending to the chat list
- Skip appending entries with invalid or empty profile names to enhance data integrity
- Maintain existing chat list structure while refining data handling
=> Improve profile name validation in UniqueChatList view

whatsapp_apis/views.py
- Update match query to include a condition ensuring phone numbers have a length of 12 characters
- Improve data validation for user IDs in chat list retrieval
- Maintain existing functionality while refining data integrity checks
=> Enhance user ID matching in UniqueChatList view

whatsapp_apis/views.py
- Implement timezone conversion to IST for last_message_time in chat list data
- Ensure proper handling of naive timestamps by localizing them to UTC before conversion
- Maintain existing chat list structure while enhancing time representation for better user experience
=> Add timezone conversion for last message time in UniqueChatList view

send_scheduled_message.py
- Update target_days to remove the 30-day option for scheduling
- Enhance date parsing to handle both string formats and datetime objects
- Adjust date formatting in the message payload to use "dd-mm-yyyy"
- Ensure text field is included only if present in the user record
=> Refactor date handling in scheduled message processing

utils/whatsapp_message_data.py
- Update logic to extract template text specifically from components of type "BODY"
- Improve clarity by renaming the "Name" key to "name" in the message details dictionary
- Enhance debugging output by printing the extracted template text
=> Refactor template text extraction in send_message_data function

ai_apis/views.py
- Change the metadata parameter to use msg_data for improved clarity and consistency
- Ensure proper data structure is maintained while enhancing the message processing logic
=> Update metadata handling in SendMessage view

ai_apis/views.py, utils/whatsapp_message_data.py
- Remove unnecessary print statements to clean up the code and improve performance
- Update header processing logic to ensure image URLs are only added when present
- Maintain existing functionality while enhancing the clarity and efficiency of the message processing logic
=> Refactor logging and image header processing in WhatsApp message data

utils/whatsapp_message_data.py
- Introduce logic to handle body parameters for message components, ensuring proper formatting for both text and URL types
- Refactor button entry creation to streamline the addition of parameters based on button type
- Maintain existing functionality while improving the clarity and efficiency of message processing
=> Enhance body and button processing in WhatsApp message data

utils/whatsapp_message_data.py
- Introduce conditional logic to append button entries only when the "example" key is present in the buttons dictionary
- Maintain existing functionality while improving the clarity and efficiency of button handling in message components
=> Refine button entry creation in WhatsApp message data processing

utils/whatsapp_message_data.py
- Remove redundant body processing logic in the `process_components` function to streamline message handling
- Update logging to print the HTTP response status code instead of the entire response object for better debugging
- Maintain existing functionality while enhancing code readability and efficiency
=> Refactor WhatsApp message data processing for improved clarity

utils/database.py, whatsapp_apis/views.py
- Add a new `format_date` function to standardize date string formatting based on the difference from the current date
- Remove unnecessary print statement in the MongoDB class to enhance code cleanliness
- Maintain existing functionality while improving date handling and code readability
=> Implement date formatting utility and clean up database logging

whatsapp_apis/views.py
- Comment out the invalid customer details check to allow for more flexible handling of customer data
- Update customer details assignment to provide fallback values when customer information is not found
- Maintain existing functionality while improving the robustness of customer data retrieval
=> Refactor customer details handling in CustomersChatLogs view

whatsapp_apis/views.py
- Extend the message status check to include 'failed' as a valid status, improving the accuracy of message type classification
- Maintain existing functionality while enhancing the robustness of message processing logic
=> Update message status handling in CustomersChatLogs view

send_scheduled_message.py
- Introduce logic to ensure unique records based on the 'number' field, improving the accuracy of the messages sent.
- Maintain existing functionality while enhancing the clarity and efficiency of the scheduled message processing.
=> Enhance filtering of scheduled messages in send_scheduled_message.py

send_scheduled_message.py
- Enhance the error reporting in the fetch_scheduled_messages function by including the line number where the error occurred, providing better context for debugging.
- Maintain existing functionality while improving the clarity of error messages for easier troubleshooting.
=> Improve error handling in scheduled message generation

send_scheduled_message.py
- Enhance the fetch_scheduled_messages function to support date parsing from float timestamps, allowing for more flexible date input.
- Maintain existing functionality while improving the robustness of date handling in scheduled message records.
=> Add date handling for float timestamps in scheduled messages

send_scheduled_message.py
- Enhance error handling for date parsing by specifying ValueError exceptions, ensuring only valid date strings are processed.
- Add checks to skip NaN values when handling float timestamps, improving the robustness of date handling in scheduled messages.
- Maintain existing functionality while increasing the reliability of date input processing.
=> Improve date validation in fetch_scheduled_messages function

utils/whatsapp_message_data.py
- Replace API_KEY with API_TOKEN for authorization in the send_message_data function, ensuring consistent usage of the token for user identification.
- Maintain existing functionality while improving clarity in API interactions.
=> Refactor API token usage in send_message_data function for consistency

utils/whatsapp_message_data.py
- Assign API_KEY to API_TOKEN for authorization in the send_message_data function, ensuring consistent token usage for user identification.
- Maintain existing functionality while enhancing clarity in API interactions.
=> Update API_TOKEN assignment in send_message_data function for clarity

utils/whatsapp_message_data.py
- Change date format from "%Y-%m-%d %H:%M:%S" to "%d-%m-%Y" for improved readability.
- Implement error handling to ensure robustness when converting date objects.
- Maintain existing functionality while enhancing the clarity of date representation in messages.
=> Update date formatting in send_message_data function for consistency

ai_apis/schedule_task.py
- Introduce try-except blocks to improve error handling during customer data processing and message scheduling.
- Refactor customer data creation and update logic for clarity and maintainability.
- Ensure existing functionality is preserved while enhancing robustness in the scheduling process.
=> Enhance error handling and customer data processing in schedule_task.py
